version: '3'

services:
  app:
    build:
      context: ./
      dockerfile: docker/dev/app/Dockerfile
    image: hello-world-dev
    container_name: app_container
    ports:
      - 8080:8080
    tty: true
    volumes:
      - ./:/var/www/html/server
    environment:
      - DB_URL=jdbc:mysql://db_container:3306/hello_world
      - USERNAME=admin
      - PASSWORD=password
    working_dir: /var/www/html/server
    networks:
      - app-net

  db:
    build:
      context: docker/dev/db
      dockerfile: Dockerfile
    image: hello-world-db-dev
    container_name: db_container
    platform: linux/amd64
    ports:
      - "3306:3306"
    volumes:
      # docker-compose.ymlの階層から
      - ./docker/dev/db/settings:/etc/mysql/conf.d/
      - ./docker/dev/db/data/:/var/lib/mysql/
      - ./docker/dev/db/script:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: hello_world
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root_password
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
