version: '3'

services:
  app:
    build:
      context: ./
      dockerfile: ./docker/app/Dockerfile
    image: hello-world
    container_name: app_container
    ports:
      - 8080:8080
    tty: true
    volumes:
      - ./:/var/www/html/server
    working_dir: /var/www/html/server
    networks:
      - app-net

  db:
    build:
      context: ./docker/db
      dockerfile: Dockerfile
    image: hello-world-db
    container_name: db_container
    platform: linux/amd64
    ports:
      - "3306:3306"
    volumes:
      - /settings:/etc/mysql/conf.d/
      - /data/:/var/lib/mysql/
      - /script:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: hello_world
      MYSQL_ROOT_PASSWORD: password
    networks:
      - app-net

networks:
  app-net:
    driver: bridge